# -*- coding: utf-8 -*-
"""Despliegue_trabajo_final_red_neuronalV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u2nkZrsqDJnX4A3mgMwNZov7fLx-Hrim

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st
st.title('Predicción de riesgo de hipertensión Arterial')
edad= st.slider('Edad', min_value=9, max_value=90, value=30, step=1)
concentracion_hemoglobina= st.slider('concentracion_hemoglobina', min_value=8, max_value=18, value=100, step=1)
valor_colesterol_ldl = st.slider('valor_colesterol_ldl', min_value=20, max_value=90, value=80, step=1)
resultado_glucosa = st.slider('resultado_glucosa', min_value=50, max_value=250, value=100, step=1)
valor_insulina = st.slider('valor_insulina', min_value=2.0, max_value=25.0, value=15.0, step=0.5)
valor_trigliceridos = st.slider('valor_trigliceridos', min_value=30, max_value=400, value=150, step=1)
valor_folato = st.slider('valor_folato', min_value=4.0, max_value=25.0, value=10.0, step=0.1)
valor_homocisteina = st.slider('valor_homocisteina', min_value=5.0, max_value=30.0, value=12.0, step=0.1)
valor_vitamina_bdoce = st.slider('valor_vitamina_bdoce', min_value=200, max_value=900, value=400, step=1)
valor_vitamina_d = st.slider('valor_vitamina_d', min_value=10, max_value=100, value=50, step=1)
estatura = st.slider('estatura', min_value=70.0, max_value=210.0, value=160.0, step=0.5)
distancia_rodilla_talon = st.slider('distancia_rodilla_talon', min_value=30.0, max_value=70.0, value=45.0, step=0.5)
circunferencia_de_la_pantorrilla = st.slider('circunferencia_de_la_pantorrilla', min_value=20.0, max_value=60.0, value=34.0, step=0.5)
tension_arterial = st.slider('tension_arterial', min_value=80, max_value=200, value=120, step=1)
actividad_total = st.slider('actividad_total', min_value=0, max_value=7000, value=1500, step=10)

# Armar el DataFrame con los mismos nombres de variables
datos = [[
    edad, concentracion_hemoglobina, valor_colesterol_ldl, resultado_glucosa,
    valor_insulina, valor_trigliceridos, valor_folato, valor_homocisteina,
    valor_vitamina_bdoce, valor_vitamina_d, estatura, distancia_rodilla_talon,
    circunferencia_de_la_pantorrilla, tension_arterial, actividad_total]]


#Dataframe con los mismos nombres de variables
data = pd.DataFrame(datos, columns=[
    'edad','concentracion_hemoglobina','valor_colesterol_ldl','resultado_glucosa',
    'valor_insulina','valor_trigliceridos','valor_folato','valor_homocisteina',
    'valor_vitamina_bdoce','valor_vitamina_d','estatura','distancia_rodilla_talon',
    'circunferencia_de_la_pantorrilla','tension_arterial','actividad_total'])

# ============================================================
# UNIVERSIDAD PONTIFICIA BOLIVARIANA
# Proyecto Final - Minería de Datos (CRISP-DM)
# App Streamlit - Despliegue Red Neuronal
# Manteniendo EXACTAMENTE los nombres de variables del notebook
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import pickle
import json
from pathlib import Path

# ------------------------------------------------------------
# Configuración de página
# ------------------------------------------------------------
st.set_page_config(
    page_title="Predicción de riesgo de hipertensión Arterial",
    page_icon="🩺",
    layout="wide"
)

# ------------------------------------------------------------
# Estilos (no cambia nombres de variables, solo la UI)
# ------------------------------------------------------------
st.markdown("""
<style>
    .main { background-color: #F9FAFB; }
    h1, h2, h3 { color: #004b87 !important; font-weight: 700; }
    .stButton>button {
        background-color: #004b87; color: white; border-radius: 8px;
        height: 3em; width: 100%;
    }
    .stButton>button:hover { background-color: #FDB813; color: black; }
    .metric-row { display: flex; gap: 1rem; }
    footer {visibility: hidden;}
</style>
""", unsafe_allow_html=True)

# ------------------------------------------------------------
# Encabezado
# ------------------------------------------------------------
left, right = st.columns([1, 4])
with left:
    st.image("https://www.upb.edu.co/Style%20Library/UPB%20Theme/img/logo-upb.png", width=120)
with right:
    st.title("Predicción de riesgo de hipertensión Arterial 🩸")
    st.subheader("Proyecto Final - Minería de Datos (CRISP-DM)")

st.markdown("---")

# ------------------------------------------------------------
# Carga del modelo (MISMO ARCHIVO Y OBJETOS DEL NOTEBOOK)
# ------------------------------------------------------------
@st.cache_resource
def cargar_modelo():
    filename = "modelo-class-RNN.pkl"   # <- MISMO nombre del notebook
    with open(filename, "rb") as f:
        modelNN, labelencoder, variables, min_max_scaler = pickle.load(f)
    return modelNN, labelencoder, variables, min_max_scaler

try:
    modelNN, labelencoder, variables, min_max_scaler = cargar_modelo()
except Exception as e:
    st.error(f"⚠️ No pude cargar 'modelo-class-RNN.pkl': {e}")
    st.stop()

# ------------------------------------------------------------
# Entendimiento del negocio (texto)
# ------------------------------------------------------------
with st.expander("🧠 Entendimiento del Negocio", expanded=True):
    st.write(
        "Este proyecto estima el **riesgo de hipertensión arterial** a partir de "
        "variables clínicas, bioquímicas y antropométricas, siguiendo la metodología "
        "**CRISP-DM** (entendimiento, preparación, modelamiento, evaluación y despliegue)."
    )

# ------------------------------------------------------------
# INTERFAZ: Captura de variables (MISMOS NOMBRES y RANGOS DEL NOTEBOOK)
# ------------------------------------------------------------
with st.expander("🚀 Predicción en tiempo real"):
    st.write("Ajusta los valores y ejecuta la predicción.")

    # Notas:
    # - Conservamos los labels EXACTOS del notebook.
    # - Mantenemos min/max/step que aparecen en tu .ipynb y en tus capturas.

    c1, c2, c3 = st.columns(3)
    edad = c1.slider('Edad', min_value=9, max_value=90, value=30, step=1)

    concentracion_hemoglobina = c2.slider(
        'concentracion_hemoglobina', min_value=8, max_value=18, value=100, step=1
    )
    valor_colesterol_ldl = c3.slider(
        'valor_colesterol_ldl', min_value=20, max_value=90, value=80, step=1
    )

    c4, c5, c6 = st.columns(3)
    resultado_glucosa = c4.slider(
        'resultado_glucosa', min_value=50, max_value=250, value=100, step=1
    )
    valor_insulina = c5.slider(
        'valor_insulina', min_value=2.0, max_value=25.0, value=15.0, step=0.5
    )
    valor_trigliceridos = c6.slider(
        'valor_trigliceridos', min_value=30, max_value=400, value=150, step=1
    )

    c7, c8, c9 = st.columns(3)
    valor_folato = c7.slider(
        'valor_folato', min_value=4.0, max_value=25.0, value=10.0, step=0.1
    )
    valor_homocisteina = c8.slider(
        'valor_homocisteina', min_value=5.0, max_value=30.0, value=12.0, step=0.1
    )
    valor_vitamina_bdoce = c9.slider(
        'valor_vitamina_bdoce', min_value=200, max_value=900, value=400, step=1
    )

    c10, c11, c12 = st.columns(3)
    valor_vitamina_d = c10.slider(
        'valor_vitamina_d', min_value=10, max_value=100, value=50, step=1
    )
    estatura = c11.slider(
        'estatura', min_value=70.0, max_value=210.0, value=160.0, step=0.5
    )
    distancia_rodilla_talon = c12.slider(
        'distancia_rodilla_talon', min_value=30.0, max_value=70.0, value=45.0, step=0.5
    )

    c13, c14, c15 = st.columns(3)
    circunferencia_de_la_pantorrilla = c13.slider(
        'circunferencia_de_la_pantorrilla', min_value=20.0, max_value=60.0, value=34.0, step=0.5
    )
    tension_arterial = c14.slider(
        'tension_arterial', min_value=80, max_value=200, value=120, step=1
    )
    actividad_total = c15.slider(
        'actividad_total', min_value=900, max_value=7000, value=1500, step=10
    )

    # --------------------------------------------------------
    # DataFrame con los MISMOS nombres y orden de columnas
    # --------------------------------------------------------
    datos = [[
        edad, concentracion_hemoglobina, valor_colesterol_ldl, resultado_glucosa,
        valor_insulina, valor_trigliceridos, valor_folato, valor_homocisteina,
        valor_vitamina_bdoce, valor_vitamina_d, estatura, distancia_rodilla_talon,
        circunferencia_de_la_pantorrilla, tension_arterial, actividad_total
    ]]

    data = pd.DataFrame(datos, columns=[
        'edad','concentracion_hemoglobina','valor_colesterol_ldl','resultado_glucosa',
        'valor_insulina','valor_trigliceridos','valor_folato','valor_homocisteina',
        'valor_vitamina_bdoce','valor_vitamina_d','estatura','distancia_rodilla_talon',
        'circunferencia_de_la_pantorrilla','tension_arterial','actividad_total'
    ])

    # --------------------------------------------------------
    # Preparación EXACTA del aprendizaje (si hay scaler, úsalo)
    # --------------------------------------------------------
    # El pickle trae: modelNN, labelencoder, variables, min_max_scaler
    # Usamos 'variables' para asegurar el mismo orden esperado por el modelo.
    if min_max_scaler is not None:
        data_preparada = pd.DataFrame(
            min_max_scaler.transform(data[variables]),
            columns=variables
        )
    else:
        data_preparada = data[variables].copy()

    # --------------------------------------------------------
    # Botón de predicción
    # --------------------------------------------------------
    if st.button("🔍 Ejecutar Predicción"):
        with st.spinner("Ejecutando el modelo..."):
            Y_fut = modelNN.predict(data_preparada)
            # Predicción legible (si el encoder trae texto)
            try:
                pred_legible = labelencoder.inverse_transform(Y_fut)
                data['Predicción'] = pred_legible
            except Exception:
                data['Predicción'] = Y_fut

        # Mapeo solicitado: 0 = Bajo, 1 = Alto
        etiqueta_simple = "0 = Riesgo Bajo" if int(Y_fut[0]) == 0 else "1 = Riesgo Alto"

        st.success("✅ Predicción completada")
        if int(Y_fut[0]) == 1:
            st.error(f"🩺 Resultado: **{etiqueta_simple}**")
        else:
            st.info(f"✅ Resultado: **{etiqueta_simple}**")

        st.markdown("**Detalle de la predicción:**")
        st.dataframe(
            data[['distancia_rodilla_talon','circunferencia_de_la_pantorrilla',
                  'tension_arterial','actividad_total','Predicción']],
            use_container_width=True
        )

# ------------------------------------------------------------
# Métricas del modelo (opcional si existe archivo de métricas)
# ------------------------------------------------------------
with st.expander("📊 Métricas del Modelo"):
    # Si tienes un archivo 'metricas.json' con las llaves:
    # {"exactitud": 0.88, "precision": 0.88, "recall": 0.88, "roc": 0.92}
    mpath = Path("metricas.json")
    if mpath.exists():
        try:
            metricas = json.loads(mpath.read_text(encoding="utf-8"))
            c1, c2, c3, c4 = st.columns(4)
            c1.metric("Exactitud", f"{metricas.get('exactitud', 0):.2f}")
            c2.metric("Precisión", f"{metricas.get('precision', 0):.2f}")
            c3.metric("Recall", f"{metricas.get('recall', 0):.2f}")
            c4.metric("Área ROC", f"{metricas.get('roc', 0):.2f}")
        except Exception as e:
            st.warning(f"No pude leer 'metricas.json': {e}")
    else:
        st.info("Puedes crear un archivo **metricas.json** para mostrar Exactitud, Precisión, Recall y AUC.")

# ------------------------------------------------------------
# Bibliografía
# ------------------------------------------------------------
with st.expander("📚 Referencias y Bibliografía"):
    st.markdown("""
- Oviedo, A. I. (2025). *Minería de Datos en Python*. Universidad Pontificia Bolivariana.
- Oviedo, A. I. (2025). *Minería Predictiva*. Universidad Pontificia Bolivariana.
- Oviedo, A. I. (2025). *Minería Descriptiva*. Universidad Pontificia Bolivariana.
- Félix Jiménez, A. F. (s. f.). *Hipertension Arterial Mexico Data Set* [Conjunto de datos]. Kaggle.
  Recuperado el 8 de noviembre de 2025, de https://www.kaggle.com/datasets/frederickfelix/hipertensin-arterial-mxico
""")

"""# **Predicciones**
La calidad del modelo es:

- Exactirtud: 0.83
- Precisión: 0.83
- Recall: 0.82
- Area ROC: 0.89
"""